# Generated by Django 5.1.11 on 2025-08-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название места')),
                ('description_short', models.TextField(null=True, verbose_name='Краткое описание')),
                ('description_long', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('lng', models.DecimalField(decimal_places=20, max_digits=18, null=True, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=20, max_digits=18, null=True, verbose_name='Широта')),
            ],
        ),
    ]
