# Generated by Django 5.1.11 on 2025-08-19 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.DecimalField(
                decimal_places=18,
                max_digits=20,
                null=True,
                verbose_name='Широта'
                ),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.DecimalField(
                decimal_places=18,
                max_digits=20,
                null=True,
                verbose_name='Долгота'
                ),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                    )),
                ('images', models.ImageField(
                    null=True,
                    upload_to='',
                    verbose_name='Изображение'
                    )),
                ('place', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='images',
                    to='places.place',
                    verbose_name='Место'
                    )),
            ],
        ),
    ]
