# Generated by Django 5.1.11 on 2025-09-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_lat_alter_place_lng_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
