# Generated by Django 5.1.11 on 2025-09-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_order_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('place', 'order')},
        ),
    ]
