# Generated by Django 5.1.12 on 2025-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_order_alter_image_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название места'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['order'], name='places_imag_order_1f90dd_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['title'], name='places_plac_title_8ef53c_idx'),
        ),
    ]
