# Generated by Django 5.1.12 on 2025-09-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_title_image_places_imag_order_1f90dd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название места'),
        ),
    ]
