# Generated by Django 5.1.12 on 2025-09-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Позиция'),
        ),
    ]
